/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectogrupo6.Vistas;

/**
 *
 * @author Jorge Romero
 */
public class AlumnoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlumnoView
     */
    public AlumnoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAlumnoTitulo = new javax.swing.JLabel();
        jBAgregar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jLIdAlumno = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLFechNac = new javax.swing.JLabel();
        jLDni = new javax.swing.JLabel();
        jCBActivo = new javax.swing.JCheckBox();
        jTIdAlumno = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTApelldo = new javax.swing.JTextField();
        jTDni = new javax.swing.JTextField();
        jBCerrar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLAlumnoTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLAlumnoTitulo.setText("Alumno");
        getContentPane().add(jLAlumnoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 0, -1, -1));

        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 283, -1, -1));

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 283, -1, -1));

        jBBorrar.setText("Borrar");
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 283, -1, -1));

        jBModificar.setText("Modificar");
        getContentPane().add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 283, -1, -1));

        jLIdAlumno.setText("IdAlumno");
        getContentPane().add(jLIdAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, -1, -1));

        jLNombre.setText("Nombre");
        getContentPane().add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        jLApellido.setText("Apellido");
        getContentPane().add(jLApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, -1));

        jLFechNac.setText("FechNac");
        getContentPane().add(jLFechNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, -1, -1));

        jLDni.setText("Dni");
        getContentPane().add(jLDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 167, -1, -1));

        jCBActivo.setText("Activo");
        getContentPane().add(jCBActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 167, -1, -1));
        getContentPane().add(jTIdAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 48, 260, -1));
        getContentPane().add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 79, 260, -1));
        getContentPane().add(jTApelldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 110, 260, -1));
        getContentPane().add(jTDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 168, 100, -1));

        jBCerrar.setText("Cerrar");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 283, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 137, 168, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBorrarActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JCheckBox jCBActivo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLAlumnoTitulo;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLDni;
    private javax.swing.JLabel jLFechNac;
    private javax.swing.JLabel jLIdAlumno;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JTextField jTApelldo;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTIdAlumno;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
