package proyectogrupo6.Vistas;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import proyectogrupo6.Modelos.Alumno;
import proyectogrupo6.control.AlumnoData;
import proyectogrupo6.control.Conexion;

/**
 * @author Grupo 6 
 *  Fernandez Valentina
 *  Romero Jorge
 *  Gutierrez Manuel
 */
public class AlumnoView extends javax.swing.JInternalFrame {
    private AlumnoData aluData;
    /**
     * Creates new form AlumnoView
     */
    public AlumnoView(Conexion con) {
        initComponents();
        aluData = new AlumnoData(con);
        
        //fechas Maxima y Minima seleccionable
        jdcFechNac.setMaxSelectableDate(new Date());
        jdcFechNac.setMinSelectableDate(new Date(50, 0, 1));
        
        //se limpian todos los campos al abrirse la ventana
        limpiarCampos();
        
        //al principio los botones nuevo y actualizar estan desactivados
        jbNuevo.setEnabled(false);
        jbActualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAlumnoTitulo = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jLIdAlumno = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLFechNac = new javax.swing.JLabel();
        jLDni = new javax.swing.JLabel();
        jcbActivo = new javax.swing.JCheckBox();
        jtIdAlumno = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtApelldo = new javax.swing.JTextField();
        jtDni = new javax.swing.JTextField();
        jbCerrar = new javax.swing.JButton();
        jdcFechNac = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLAlumnoTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLAlumnoTitulo.setText("Alumno");

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jLIdAlumno.setText("Legajo");

        jLNombre.setText("Nombre");

        jLApellido.setText("Apellido");

        jLFechNac.setText("FechNac");

        jLDni.setText("Dni");

        jcbActivo.setText("Activo");

        jtDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDniFocusLost(evt);
            }
        });

        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLAlumnoTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLIdAlumno)
                        .addGap(38, 38, 38)
                        .addComponent(jtIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLNombre)
                        .addGap(33, 33, 33)
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLApellido)
                        .addGap(33, 33, 33)
                        .addComponent(jtApelldo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLFechNac)
                        .addGap(29, 29, 29)
                        .addComponent(jdcFechNac, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLDni)
                        .addGap(55, 55, 55)
                        .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jcbActivo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbGuardar)
                        .addGap(27, 27, 27)
                        .addComponent(jbNuevo)
                        .addGap(25, 25, 25)
                        .addComponent(jbActualizar)
                        .addGap(19, 19, 19)
                        .addComponent(jbCerrar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLAlumnoTitulo)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtApelldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFechNac, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcFechNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jcbActivo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbGuardar)
                    .addComponent(jbNuevo)
                    .addComponent(jbActualizar)
                    .addComponent(jbCerrar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        if(isInt(jtIdAlumno.getText())){
            jtIdAlumno.setEnabled(false);//no dejo que se modifique
        
                Alumno alumno = aluData.obtenerAlumnoPorId(Integer.parseInt(jtIdAlumno.getText()));

                if(alumno != null){
                    jtNombre.setText(alumno.getNombre());
                    jtApelldo.setText(alumno.getApellido());
                    jtDni.setText(alumno.getDni()+"");
                    jcbActivo.setSelected(alumno.isActivo());
                    jdcFechNac.setDate(java.sql.Date.valueOf(alumno.getFechNac()));//Date del Package java.sql

                    jbNuevo.setEnabled(true);
                    jbActualizar.setEnabled(true);
                    jbGuardar.setEnabled(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Alumno No Encontrado en la Base de Datos!");
                }
        }else{
            JOptionPane.showMessageDialog(this, "Legajo Incorrecto!");
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        limpiarCampos();
        jbGuardar.setEnabled(true);
        jbNuevo.setEnabled(false);
        jbActualizar.setEnabled(false);
        jtIdAlumno.setEnabled(true);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        if(!hayCamposVacios()){
            //obtener los datos de la vista
            String nombre = jtNombre.getText();
            String apellido = jtApelldo.getText();
            long dni = Long.parseLong(jtDni.getText());
            boolean activo = jcbActivo.isSelected();
            
            //obtener la fecha del JCalendar
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
            String fecha = formatoFecha.format(jdcFechNac.getDate());
            LocalDate fechNac = LocalDate.parse(fecha, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
            
            //lo guarda en la base de datos
            Alumno alumno = new Alumno(nombre, apellido, fechNac, dni, activo);
            if(aluData.agregarAlumno(alumno)){
                JOptionPane.showMessageDialog(this, "Alumno Guardado Exitosamente!");
                jtIdAlumno.setText(alumno.getIdAlumno()+"");
                jbNuevo.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(this, "Error al Guardar el Alumno!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Hola!");
        }
        
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDniFocusLost
        if(!isLong(jtDni.getText())){
            JOptionPane.showMessageDialog(this, "El DNI Debe Ser un Número!");
            jtDni.requestFocus();
        }
    }//GEN-LAST:event_jtDniFocusLost

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        //captura los datos de todos los campos
        if(!hayCamposVacios() && isLong(jtDni.getText())){
            /*1*/int id = Integer.parseInt(jtIdAlumno.getText());
            
            /*2*/long dni = Long.parseLong(jtDni.getText());

            /*3*/String nombre = jtNombre.getText();
            /*4*/String apellido = jtApelldo.getText();
            //obtener la fecha del JCalendar
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
            String fecha = formatoFecha.format(jdcFechNac.getDate());
            /*5*/LocalDate fechNac = LocalDate.parse(fecha, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
            /*6*/boolean activo = jcbActivo.isSelected();

            //crea un alumno con los datos modificados y lo guarda en la BD
            Alumno alumno = new Alumno(id, nombre, apellido, fechNac, dni, activo);
            if(aluData.modificarAlumno(alumno)){
                JOptionPane.showMessageDialog(this, "Alumno Modificado con Éxito!");
                jtIdAlumno.setEnabled(true);
                jbActualizar.setEnabled(false);
                jbGuardar.setEnabled(true);
                jbNuevo.setEnabled(false);
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(this, "No se Pudo Modificar el Alumno!");
            }
        }else{
            if(hayCamposVacios()){
                JOptionPane.showMessageDialog(this, "Hay Campos Vacios o Incorrectos!");
            }
        }
        
    }//GEN-LAST:event_jbActualizarActionPerformed

    /**
     * Resetea todos los campos
     */
    private void limpiarCampos(){
        jtIdAlumno.setText("");
        jtNombre.setText("");
        jtApelldo.setText("");
        jtDni.setText("");
        jcbActivo.setSelected(true);
        jdcFechNac.setDate(null);
    }
    
    /**
     * Comprueba que no haya campos vacios
     * @return true si hay algun campo vacio, de lo contrario retorna false
     */
    private boolean hayCamposVacios(){
        String ape = jtApelldo.getText();
        String nom = jtNombre.getText();
        String dni = jtDni.getText();
        
        return ape.isEmpty() || nom.isEmpty() || dni.isEmpty() || jdcFechNac.getDate() == null;
    }
    
    /**
     * comprueba que un String sea un int
     * @param n es el String que se comprueeba
     * @return true si es un int, false si no 
     */
    private boolean isInt(String n){
        try{
            int a = Integer.parseInt(n);
            return true;
        }catch(NumberFormatException nfe){
            return false;
        }
    }
    
    /**
     * comprueba que un String sea un long
     * @param n es el String que se comprueeba
     * @return true si es un long, false si no 
     */
    private boolean isLong(String n){
        try{
            long a = Long.parseLong(n);
            return true;
        }catch(NumberFormatException nfe){
            return false;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JLabel jLAlumnoTitulo;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLDni;
    private javax.swing.JLabel jLFechNac;
    private javax.swing.JLabel jLIdAlumno;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JCheckBox jcbActivo;
    private com.toedter.calendar.JDateChooser jdcFechNac;
    private javax.swing.JTextField jtApelldo;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtIdAlumno;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
