package proyectogrupo6.Vistas;

import java.awt.Color;
import javax.swing.JOptionPane;
import proyectogrupo6.control.Conexion;
import proyectogrupo6.control.MateriaData;
import proyectogrupo6.Modelos.Materia;

/**
 * @author Grupo 6 
 *  Fernandez Valentina
 *  Amieva Agustina
 *  Romero Jorge
 *  Gutierrez Manuel
 */
public class MateriaView extends javax.swing.JInternalFrame {

    private MateriaData md = null;
    private boolean numberOk;

    /**
     * Creates new form MateriaView
     */
    public MateriaView(Conexion conexion) {
        initComponents();
        this.md = new MateriaData(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLMateria = new javax.swing.JLabel();
        jLIdMateria = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jTFIdMateria = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jLAño = new javax.swing.JLabel();
        jCBActivo = new javax.swing.JCheckBox();
        jBGuardar = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jCBAnioMateria = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLMateria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLMateria.setText("Materia");

        jLIdMateria.setText("IdMateria");

        jLNombre.setText("Nombre");

        jTFIdMateria.setToolTipText("Solo se admiten numeros.");
        jTFIdMateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFIdMateriaFocusLost(evt);
            }
        });

        jTFNombre.setToolTipText("No se guarda una materia sin nombre.");

        jLAño.setText("Año");

        jCBActivo.setSelected(true);
        jCBActivo.setText("Activo");

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBBorrar.setText("Borrar");
        jBBorrar.setEnabled(false);
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });

        jBModificar.setText("Actualizar");
        jBModificar.setEnabled(false);
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBCerrar.setText("Cerrar");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jCBAnioMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero", "Segundo", "Tercero", "Cuarto", "Quinto" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(jLMateria))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jLAño)
                            .addGap(43, 43, 43)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jCBAnioMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(jCBActivo))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jBGuardar)
                            .addGap(19, 19, 19)
                            .addComponent(jBBorrar)
                            .addGap(17, 17, 17)
                            .addComponent(jBModificar)
                            .addGap(18, 18, 18)
                            .addComponent(jBCerrar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLIdMateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFIdMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jBBuscar)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLMateria)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFIdMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLIdMateria))
                    .addComponent(jBBuscar))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBAnioMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAño)
                    .addComponent(jCBActivo))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBGuardar)
                    .addComponent(jBBorrar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBModificar)
                        .addComponent(jBCerrar)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(500, 150, 370, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        if (jTFNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacio");
        } else {
            String nombre = jTFNombre.getText();
            int anio = jCBAnioMateria.getSelectedIndex() + 1;
            Boolean activo = jCBActivo.isSelected();
            Materia unaMateria = new Materia(nombre, anio, activo);
            if (md.agregarMateria(unaMateria)) {
                JOptionPane.showMessageDialog(this, "Materia agregada con éxito");
                jTFIdMateria.setText(unaMateria.getIdMateria() + "");
            } else {
                JOptionPane.showMessageDialog(this, "La materia no se agrego");
            }
            limpiar();
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTFIdMateriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFIdMateriaFocusLost
        // TODO add your handling code here:
        try {
            if (jTFIdMateria.getText().isEmpty()) {
                numberOk = false;
                jTFIdMateria.setForeground(null);
                limpiar();
                intercambiarBotones(false);
            } else {
                jTFIdMateria.setForeground(null);
                Integer.parseInt(jTFIdMateria.getText());
                numberOk = true;
            }
        } catch (Exception ex) {
            numberOk = false;
            jTFIdMateria.setForeground(Color.RED);
            jTFIdMateria.requestFocus();
        }
    }//GEN-LAST:event_jTFIdMateriaFocusLost

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        if (numberOk) {
            try {
                Materia unaMateria = md.obtenerMateriaXId(Integer.parseInt(jTFIdMateria.getText()));
                if (unaMateria != null) {
                    jTFNombre.setText(unaMateria.getNombre());
                    jCBAnioMateria.setSelectedIndex(unaMateria.getAnio() - 1);
                    jCBActivo.setSelected(unaMateria.isActivo());
                    intercambiarBotones(true);
                } else {
                    JOptionPane.showMessageDialog(this, "No existe una materia con es Id");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Id Inválido");
            }
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
        int id = -1;
        id = Integer.parseInt(jTFIdMateria.getText());
        String nom = jTFNombre.getText();
        int anio = jCBAnioMateria.getSelectedIndex() + 1;
        boolean estado = jCBActivo.isSelected();
        Materia unaMateria = new Materia(id, nom, anio, estado);
        if (md.modificarMateria(unaMateria)) {
            JOptionPane.showMessageDialog(this, "Materia modificada con éxito");
            limpiar();
            intercambiarBotones(false);
        } else {
            JOptionPane.showMessageDialog(this, "La materia no se modifico");
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        // TODO add your handling code here:
        int id = -1;
        id = Integer.parseInt(jTFIdMateria.getText());
        if (md.borrarMateria(id)) {
            JOptionPane.showMessageDialog(this, "Materia borrada con éxito");
            limpiar();
            intercambiarBotones(false);
        } else {
            JOptionPane.showMessageDialog(this, "La materia no se borro");
        }
    }//GEN-LAST:event_jBBorrarActionPerformed

    private void limpiar() {
        this.jTFIdMateria.setText("");
        this.jTFNombre.setText("");
        this.jCBAnioMateria.setSelectedIndex(0);
    }

    private void intercambiarBotones(boolean b) {
        jBGuardar.setEnabled(!b);
        jCBActivo.setEnabled(!b);
        jBBorrar.setEnabled(b);
        jBModificar.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JCheckBox jCBActivo;
    private javax.swing.JComboBox<String> jCBAnioMateria;
    private javax.swing.JLabel jLAño;
    private javax.swing.JLabel jLIdMateria;
    private javax.swing.JLabel jLMateria;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFIdMateria;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}
