/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectogrupo6.Vistas;


/**
 *
 * @author Jorge Romero
 */
public class MateriaView extends javax.swing.JInternalFrame {
    

    /**
     * Creates new form MateriaView
     */
    public MateriaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLMateria = new javax.swing.JLabel();
        jLIdMateria = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jTFIdMateria = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jLAño = new javax.swing.JLabel();
        jCBActivo = new javax.swing.JCheckBox();
        jBGuardar = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLMateria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLMateria.setText("Materia");
        jPanel1.add(jLMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jLIdMateria.setText("IdMateria");
        jPanel1.add(jLIdMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, -1, -1));

        jLNombre.setText("Nombre");
        jPanel1.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, -1));

        jTFIdMateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFIdMateriaFocusLost(evt);
            }
        });
        jPanel1.add(jTFIdMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, -1));

        jTFNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFNombreFocusLost(evt);
            }
        });
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 202, -1));

        jLAño.setText("Año");
        jPanel1.add(jLAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jCBActivo.setText("Activo");
        jCBActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBActivoActionPerformed(evt);
            }
        });
        jPanel1.add(jCBActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jBBorrar.setText("Borrar");
        jPanel1.add(jBBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jBModificar.setText("Actualizar");
        jPanel1.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jBCerrar.setText("Cerrar");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jButton1.setText("Buscar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 122, 107, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBActivoActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTFIdMateriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFIdMateriaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdMateriaFocusLost

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jTFNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreFocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCBActivo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLAño;
    private javax.swing.JLabel jLIdMateria;
    private javax.swing.JLabel jLMateria;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFIdMateria;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}